config: conf/linear_regression.yaml
inherit:
- base.yaml
model:
  family: gpt2
  n_dims: 1
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 101
out_dir: ../models/linear_regression
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 1
      inc: 0
      interval: 2000
      start: 1
    points:
      end: 41
      inc: 0
      interval: 2000
      start: 41
  data: gaussian
  keep_every_steps: 5000
  learning_rate: 0.0001
  num_tasks: null
  resume_id: finetuned1
  save_every_steps: 1000
  task: linear_regression
  task_kwargs: {}
  input_kwargs:
    bias: 0
    scale: 10
  train_steps: 100001
wandb:
  entity: in-context
  log_every_steps: 100
  name: linear_regression_finetuned
  notes: ''
  project: in-context-training
